name: "Skopeo Copy"
description: "Copy an image from one registry to another"

inputs:
  version:
    description: "The version of skopeo to use. Currently valid: 1.8.0, 1.7.0"
    required: false
    default: 1.8.0
  srcTransport:
    description: The transport to use for the source image.
    required: false
    default: docker
  dstTransport:
    description: The transport to use for the destination image.
    required: false
    default: docker
  srcImg:
    description: The fully qualified source image (e.g. quay.io/myrepo/image:tag)
    required: true
  dstImg:
    description: The fully qualified destination image (e.g. quay.io/myrepo/image:tag)
    required: true
  skopeoCopyFlags:
    description: Any flags to pass to `skopeo copy`. This is not validated, and may cause broken pipelines if set incorrectly.
    required: false
  username:
    description: Username used to authenticate to the registry.
    required: true
  password:
    description: Password used to authenticate to the registry.
    required: true
  registry:
    description: The registry to authenticate against. This is temporarily required.
    required: true
runs:
  using: "docker"
  image: quay.io/komish/skopeo-multibin:0.0.3